### ISSUE TITLE
Can't launch the server,help me

### ISSUE THREAD

**Issue by icemanjin** [palantir/python-jsonrpc-server#41]
D:\work\onlinepythonedit\work\online_python_edit_and_run\app\languageServer> python .\python_server.py
Traceback (most recent call last):
  File ".\python_server.py", line 74, in <module>
    app.listen(3000, address='127.0.0.1')
  File "E:\Program Files\python\lib\site-packages\tornado\web.py", line 2116, in listen
    server.listen(port, address)
  File "E:\Program Files\python\lib\site-packages\tornado\tcpserver.py", line 152, in listen
    self.add_sockets(sockets)
  File "E:\Program Files\python\lib\site-packages\tornado\tcpserver.py", line 165, in add_sockets
    self._handlers[sock.fileno()] = add_accept_handler(
  File "E:\Program Files\python\lib\site-packages\tornado\netutil.py", line 279, in add_accept_handler
    io_loop.add_handler(sock, accept_handler, IOLoop.READ)
  File "E:\Program Files\python\lib\site-packages\tornado\platform\asyncio.py", line 100, in add_handler
    self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
  File "E:\Program Files\python\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError

**Comment by bnavigator** [comment]
Without more information about your environment, this is impossible to determine.

My guess: You have to update python, tornado and asyncio and make sure all the dependencies are met.
